language: bash

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.25.4
  DOCKER_COMPOSE_YML: ./docker-compose.yml

# This installs docker-compose
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker-compose -f ${DOCKER_COMPOSE_YML} build

script:
  - TEST=y docker-compose -f ${DOCKER_COMPOSE_YML} up --abort-on-container-exit
